/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyEngineForPolicy,
  IPolicyEngineForPolicyInterface,
} from "../../../../../contracts/bufi/policies/DisputeWindowPolicy.sol/IPolicyEngineForPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "PolicyRejected",
    type: "error",
  },
] as const;

export class IPolicyEngineForPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyEngineForPolicyInterface {
    return new Interface(_abi) as IPolicyEngineForPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyEngineForPolicy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPolicyEngineForPolicy;
  }
}
