import type { ContractTemplate } from '@bu/contracts/contract-flow'
import { createNode, createEdge } from '@bu/contracts/contract-flow'

// ============================================
// PAYMENT TEMPLATES (8) - Escrow + AI verification + yield
// ============================================

export const contractTemplates: ContractTemplate[] = [
  {
    id: 'freelance-service',
    name: 'Freelance Service Agreement',
    description: 'Single deliverable contract with IP assignment toggle, milestone payments, and dual signatures.',
    icon: 'Briefcase',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Client', name: '', email: '', role: 'payer' }),
      createNode('milestone-1', 'milestone', { x: 350, y: 100 }, { label: 'Project Kickoff', title: 'Project Kickoff', description: 'Initial project setup and requirements gathering', amount: 1000, currency: 'USDC', verificationCriteria: 'Requirements document approved' }),
      createNode('milestone-2', 'milestone', { x: 350, y: 300 }, { label: 'Final Delivery', title: 'Final Delivery', description: 'Complete project delivery with all deliverables', amount: 2000, currency: 'USDC', verificationCriteria: 'All deliverables approved by client' }),
      createNode('signature-payer', 'signature', { x: 600, y: 100 }, { label: 'Client Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Freelancer Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payment-1', 'payment', { x: 850, y: 200 }, { label: 'Release Payment', amount: 3000, currency: 'USDC', triggerType: 'milestone-completion' }),
      createNode('payee-1', 'party-payee', { x: 1100, y: 200 }, { label: 'Freelancer', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'milestone-1'),
      createEdge('e2', 'payer-1', 'milestone-2'),
      createEdge('e3', 'milestone-1', 'signature-payer'),
      createEdge('e4', 'milestone-2', 'signature-payee'),
      createEdge('e5', 'signature-payer', 'payment-1'),
      createEdge('e6', 'signature-payee', 'payment-1'),
      createEdge('e7', 'payment-1', 'payee-1'),
    ],
  },
  {
    id: 'milestone-project',
    name: 'Multi-Milestone Project',
    description: 'Multi-phase project with progressive payments (30/30/40), conditional logic, and progress tracking.',
    icon: 'Target',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 250 }, { label: 'Project Owner', name: '', email: '', role: 'payer' }),
      createNode('milestone-1', 'milestone', { x: 350, y: 50 }, { label: 'Phase 1: Discovery', title: 'Discovery Phase', description: 'Research and planning', amount: 3000, currency: 'USDC', verificationCriteria: 'Discovery report approved' }),
      createNode('milestone-2', 'milestone', { x: 350, y: 175 }, { label: 'Phase 2: Design', title: 'Design Phase', description: 'UI/UX design and prototypes', amount: 3000, currency: 'USDC', verificationCriteria: 'Design mockups approved' }),
      createNode('milestone-3', 'milestone', { x: 350, y: 300 }, { label: 'Phase 3: Development', title: 'Development Phase', description: 'Full implementation', amount: 4000, currency: 'USDC', verificationCriteria: 'All features implemented and tested' }),
      createNode('condition-1', 'condition', { x: 600, y: 175 }, { label: 'All Phases Complete?', type: 'approval', condition: 'All milestones marked as complete', trueLabel: 'Proceed', falseLabel: 'Review' }),
      createNode('signature-payer', 'signature', { x: 850, y: 100 }, { label: 'Owner Approval', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 850, y: 250 }, { label: 'Team Confirmation', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payment-1', 'payment', { x: 1100, y: 175 }, { label: 'Final Payment', amount: 10000, currency: 'USDC', triggerType: 'milestone-completion' }),
      createNode('payee-1', 'party-payee', { x: 1350, y: 175 }, { label: 'Development Team', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'milestone-1'),
      createEdge('e2', 'milestone-1', 'milestone-2'),
      createEdge('e3', 'milestone-2', 'milestone-3'),
      createEdge('e4', 'milestone-3', 'condition-1'),
      createEdge('e5', 'condition-1', 'signature-payer', 'true'),
      createEdge('e6', 'condition-1', 'signature-payee', 'true'),
      createEdge('e7', 'signature-payer', 'payment-1'),
      createEdge('e8', 'signature-payee', 'payment-1'),
      createEdge('e9', 'payment-1', 'payee-1'),
    ],
  },
  {
    id: 'retainer-subscription',
    name: 'Retainer / Subscription',
    description: 'Recurring monthly payments with rollover hours, auto-renewal options, and service terms.',
    icon: 'RefreshCw',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Client', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 100 }, { label: 'Service Terms', title: 'Monthly Service Terms', content: 'Client agrees to pay a monthly retainer for ongoing services. Unused hours roll over to the next month (max 10 hours). Auto-renews unless cancelled with 30 days notice.', aiGenerated: false }),
      createNode('milestone-1', 'milestone', { x: 350, y: 250 }, { label: 'Monthly Retainer', title: 'Monthly Service Delivery', description: 'Ongoing monthly service delivery (40 hours)', amount: 5000, currency: 'USDC', verificationCriteria: 'Monthly deliverables completed' }),
      createNode('signature-payer', 'signature', { x: 600, y: 150 }, { label: 'Client Approval', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Provider Confirmation', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payment-1', 'payment', { x: 850, y: 200 }, { label: 'Monthly Payment', amount: 5000, currency: 'USDC', triggerType: 'time-based' }),
      createNode('payee-1', 'party-payee', { x: 1100, y: 200 }, { label: 'Service Provider', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'milestone-1'),
      createEdge('e3', 'milestone-1', 'signature-payer'),
      createEdge('e4', 'milestone-1', 'signature-payee'),
      createEdge('e5', 'signature-payer', 'payment-1'),
      createEdge('e6', 'signature-payee', 'payment-1'),
      createEdge('e7', 'payment-1', 'payee-1'),
    ],
  },
  {
    id: 'agency-partnership',
    name: 'Agency Partnership',
    description: 'Revenue share agreement with commission splits supporting up to 3 parties.',
    icon: 'Users',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 250 }, { label: 'End Client', name: '', email: '', role: 'payer' }),
      createNode('milestone-1', 'milestone', { x: 350, y: 150 }, { label: 'Project Scope', title: 'Scope Definition', description: 'Define project requirements and timeline', amount: 0, currency: 'USDC', verificationCriteria: 'Scope document signed' }),
      createNode('milestone-2', 'milestone', { x: 350, y: 350 }, { label: 'Project Completion', title: 'Final Delivery', description: 'Complete project delivery', amount: 10000, currency: 'USDC', verificationCriteria: 'Client acceptance' }),
      createNode('signature-payer', 'signature', { x: 600, y: 150 }, { label: 'Client Sign-off', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 350 }, { label: 'Provider Sign-off', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('commission-1', 'commission', { x: 850, y: 100 }, { label: 'Agency Commission', recipientName: 'Partner Agency', recipientAddress: '', percentage: 10 }),
      createNode('payment-1', 'payment', { x: 850, y: 350 }, { label: 'Provider Payment', amount: 9000, currency: 'USDC', triggerType: 'milestone-completion' }),
      createNode('payee-1', 'party-payee', { x: 1100, y: 100 }, { label: 'Agency', name: '', email: '', role: 'payee' }),
      createNode('payee-2', 'party-payee', { x: 1100, y: 350 }, { label: 'Service Provider', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'milestone-1'),
      createEdge('e2', 'milestone-1', 'milestone-2'),
      createEdge('e3', 'milestone-2', 'signature-payer'),
      createEdge('e4', 'milestone-2', 'signature-payee'),
      createEdge('e5', 'signature-payer', 'commission-1'),
      createEdge('e6', 'signature-payee', 'payment-1'),
      createEdge('e7', 'commission-1', 'payee-1'),
      createEdge('e8', 'payment-1', 'payee-2'),
    ],
  },
  {
    id: 'influencer-campaign',
    name: 'Influencer Campaign',
    description: 'Content creation with specs, posting schedule, and performance bonuses.',
    icon: 'Video',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Brand', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 50 }, { label: 'Content Specs', title: 'Content Requirements', content: '1x Instagram Reel (60-90s), 1x Story set (3-5 frames), 2x feed posts. Must include brand mention and CTA link in bio.', aiGenerated: false }),
      createNode('milestone-1', 'milestone', { x: 350, y: 175 }, { label: 'Content Brief', title: 'Brief Approval', description: 'Approve content concept and script', amount: 500, currency: 'USDC', verificationCriteria: 'Brief approved by brand' }),
      createNode('milestone-2', 'milestone', { x: 350, y: 300 }, { label: 'Content Delivery', title: 'Content Creation', description: 'Deliver final content assets', amount: 2000, currency: 'USDC', verificationCriteria: 'Content meets brand guidelines' }),
      createNode('signature-payer', 'signature', { x: 600, y: 175 }, { label: 'Brand Approval', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Creator Confirmation', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('condition-1', 'condition', { x: 850, y: 300 }, { label: 'Performance Bonus?', type: 'if-else', condition: 'Content exceeds 100K views', trueLabel: 'Bonus', falseLabel: 'Standard' }),
      createNode('payment-1', 'payment', { x: 850, y: 175 }, { label: 'Base Payment', amount: 2500, currency: 'USDC', triggerType: 'milestone-completion' }),
      createNode('payment-2', 'payment', { x: 1100, y: 300 }, { label: 'Performance Bonus', amount: 1000, currency: 'USDC', triggerType: 'manual' }),
      createNode('payee-1', 'party-payee', { x: 1100, y: 175 }, { label: 'Creator', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'milestone-1'),
      createEdge('e3', 'milestone-1', 'milestone-2'),
      createEdge('e4', 'milestone-2', 'signature-payer'),
      createEdge('e5', 'milestone-2', 'signature-payee'),
      createEdge('e6', 'signature-payer', 'payment-1'),
      createEdge('e7', 'signature-payee', 'condition-1'),
      createEdge('e8', 'condition-1', 'payment-2', 'true'),
      createEdge('e9', 'payment-1', 'payee-1'),
      createEdge('e10', 'payment-2', 'payee-1'),
    ],
  },
  {
    id: 'trade-invoice',
    name: 'Trade Invoice',
    description: 'International trade with Incoterms selector (EXW/FOB/CIF/DDP), shipment tracking, and inspection.',
    icon: 'Ship',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 250 }, { label: 'Importer / Buyer', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 100 }, { label: 'Trade Terms', title: 'INCOTERMS 2020', content: 'This agreement follows INCOTERMS 2020 - FOB (Free On Board). Seller responsible for export clearance. Risk transfers when goods pass ship rail at port of shipment.', aiGenerated: false }),
      createNode('milestone-1', 'milestone', { x: 350, y: 250 }, { label: 'Goods Shipped', title: 'Shipment Confirmation', description: 'Goods shipped with tracking number', amount: 0, currency: 'USDC', verificationCriteria: 'Bill of Lading provided' }),
      createNode('milestone-2', 'milestone', { x: 600, y: 250 }, { label: 'Goods Received', title: 'Delivery & Inspection', description: 'Goods delivered and inspection passed', amount: 0, currency: 'USDC', verificationCriteria: 'Inspection report approved' }),
      createNode('signature-payer', 'signature', { x: 850, y: 175 }, { label: 'Buyer Acceptance', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 850, y: 325 }, { label: 'Seller Confirmation', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payment-1', 'payment', { x: 1100, y: 250 }, { label: 'Release Escrow', amount: 50000, currency: 'USDC', triggerType: 'milestone-completion' }),
      createNode('payee-1', 'party-payee', { x: 1350, y: 250 }, { label: 'Exporter / Seller', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'milestone-1'),
      createEdge('e3', 'milestone-1', 'milestone-2'),
      createEdge('e4', 'milestone-2', 'signature-payer'),
      createEdge('e5', 'milestone-2', 'signature-payee'),
      createEdge('e6', 'signature-payer', 'payment-1'),
      createEdge('e7', 'signature-payee', 'payment-1'),
      createEdge('e8', 'payment-1', 'payee-1'),
    ],
  },
  {
    id: 'consulting-engagement',
    name: 'Consulting Engagement',
    description: 'Hourly or project rate with embedded NDA, non-compete toggle, and periodic payments.',
    icon: 'MessageSquare',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Client Company', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 75 }, { label: 'Scope of Work', title: 'Consulting Scope', content: 'Consultant will provide advisory services including strategic planning, process optimization, and team training. Rate: $200/hour or $15,000/month retainer.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 200 }, { label: 'Confidentiality', title: 'NDA Terms', content: 'All information shared during the engagement remains strictly confidential for 3 years post-termination.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 325 }, { label: 'Non-Compete', title: 'Non-Compete Clause', content: 'Consultant agrees not to work with direct competitors during engagement and for 6 months after.', aiGenerated: false }),
      createNode('milestone-1', 'milestone', { x: 600, y: 200 }, { label: 'Monthly Hours', title: 'Monthly Consulting', description: 'Up to 40 hours of consulting per month', amount: 8000, currency: 'USDC', verificationCriteria: 'Timesheet approved by client' }),
      createNode('signature-payer', 'signature', { x: 850, y: 125 }, { label: 'Client Approval', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 850, y: 275 }, { label: 'Consultant Confirmation', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payment-1', 'payment', { x: 1100, y: 200 }, { label: 'Monthly Payment', amount: 8000, currency: 'USDC', triggerType: 'time-based' }),
      createNode('payee-1', 'party-payee', { x: 1350, y: 200 }, { label: 'Consultant', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'payer-1', 'clause-2'),
      createEdge('e3', 'payer-1', 'clause-3'),
      createEdge('e4', 'clause-1', 'milestone-1'),
      createEdge('e5', 'clause-2', 'milestone-1'),
      createEdge('e6', 'milestone-1', 'signature-payer'),
      createEdge('e7', 'milestone-1', 'signature-payee'),
      createEdge('e8', 'signature-payer', 'payment-1'),
      createEdge('e9', 'signature-payee', 'payment-1'),
      createEdge('e10', 'payment-1', 'payee-1'),
    ],
  },
  {
    id: 'creative-license',
    name: 'Creative License',
    description: 'IP licensing with exclusive/non-exclusive toggle, royalties, and usage scope definition.',
    icon: 'FileText',
    category: 'payment',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Licensee', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 100 }, { label: 'License Grant', title: 'Non-Exclusive License', content: 'Licensor grants Licensee a non-exclusive, worldwide license to use the creative works for commercial purposes. Territory: Worldwide. Term: 2 years with renewal option.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 300 }, { label: 'Usage Scope', title: 'Permitted Use', content: 'Licensed for: marketing, advertising, merchandise. Sublicensing requires written consent. Attribution required in all uses.', aiGenerated: false }),
      createNode('milestone-1', 'milestone', { x: 600, y: 200 }, { label: 'Asset Delivery', title: 'Creative Asset Delivery', description: 'Delivery of all licensed creative assets in required formats', amount: 5000, currency: 'USDC', verificationCriteria: 'All assets delivered and verified' }),
      createNode('signature-payer', 'signature', { x: 850, y: 100 }, { label: 'Licensee Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 850, y: 300 }, { label: 'Licensor Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payment-1', 'payment', { x: 1100, y: 200 }, { label: 'License Fee', amount: 5000, currency: 'USDC', triggerType: 'milestone-completion' }),
      createNode('payee-1', 'party-payee', { x: 1350, y: 200 }, { label: 'Licensor', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'payer-1', 'clause-2'),
      createEdge('e3', 'clause-1', 'milestone-1'),
      createEdge('e4', 'clause-2', 'milestone-1'),
      createEdge('e5', 'milestone-1', 'signature-payer'),
      createEdge('e6', 'milestone-1', 'signature-payee'),
      createEdge('e7', 'signature-payer', 'payment-1'),
      createEdge('e8', 'signature-payee', 'payment-1'),
      createEdge('e9', 'payment-1', 'payee-1'),
    ],
  },

  // ============================================
  // LEGAL TEMPLATES (5) - Signatures only, no payment
  // ============================================

  {
    id: 'mutual-nda',
    name: 'Mutual NDA',
    description: 'Bilateral confidentiality agreement with term/survival years and excluded information clauses.',
    icon: 'Shield',
    category: 'legal',
    tags: ['legal'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 175 }, { label: 'Party A', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 100 }, { label: 'Confidentiality', title: 'Mutual Confidentiality', content: 'Both parties agree to hold in confidence all Confidential Information disclosed by either party. This includes business plans, technical data, customer lists, and financial information.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 225 }, { label: 'Exclusions', title: 'Excluded Information', content: 'Confidential Information does not include: (a) publicly available information, (b) information known prior to disclosure, (c) information independently developed, (d) information received from third parties.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 350 }, { label: 'Term', title: 'Term & Survival', content: 'This Agreement is effective for 2 years. Confidentiality obligations survive for 3 years after expiration or termination.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 150 }, { label: 'Party A Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Party B Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 225 }, { label: 'Party B', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'signature-payer'),
      createEdge('e5', 'clause-3', 'signature-payee'),
      createEdge('e6', 'signature-payer', 'payee-1'),
      createEdge('e7', 'signature-payee', 'payee-1'),
    ],
  },
  {
    id: 'piia',
    name: 'PIIA (Proprietary Information)',
    description: 'IP assignment + confidentiality + non-solicit combo for employees and contractors.',
    icon: 'Lock',
    category: 'legal',
    tags: ['legal'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Company', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 75 }, { label: 'IP Assignment', title: 'Invention Assignment', content: 'Employee assigns to Company all rights in any inventions, discoveries, or improvements made during employment that relate to Company business.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 200 }, { label: 'Confidentiality', title: 'Confidential Information', content: 'Employee will not disclose or use any Confidential Information except as required in performance of duties. Obligations survive termination indefinitely.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 325 }, { label: 'Non-Solicit', title: 'Non-Solicitation', content: 'For 12 months after termination, Employee will not solicit Company employees or customers for a competing business.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 150 }, { label: 'Company Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 275 }, { label: 'Employee Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 200 }, { label: 'Employee / Contractor', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'payer-1', 'clause-2'),
      createEdge('e3', 'payer-1', 'clause-3'),
      createEdge('e4', 'clause-1', 'signature-payer'),
      createEdge('e5', 'clause-2', 'signature-payee'),
      createEdge('e6', 'signature-payer', 'payee-1'),
      createEdge('e7', 'signature-payee', 'payee-1'),
    ],
  },
  {
    id: 'statement-of-work',
    name: 'Statement of Work (SOW)',
    description: 'Links to MSA with deliverables list, timeline, and optional payment terms.',
    icon: 'ClipboardList',
    category: 'legal',
    tags: ['legal'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Client', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 100 }, { label: 'Reference', title: 'MSA Reference', content: 'This SOW is governed by the Master Service Agreement dated [DATE] between the parties. In case of conflict, MSA terms prevail.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 225 }, { label: 'Deliverables', title: 'Scope & Deliverables', content: '1. Requirements Document (Week 1-2)\n2. Design Mockups (Week 3-4)\n3. Development Build (Week 5-8)\n4. Testing & QA (Week 9-10)\n5. Final Delivery (Week 11-12)', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 350 }, { label: 'Timeline', title: 'Project Timeline', content: 'Project Duration: 12 weeks from signed SOW. Key milestones must be approved within 5 business days or deemed accepted.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 150 }, { label: 'Client Approval', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Vendor Acceptance', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 225 }, { label: 'Vendor', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'signature-payer'),
      createEdge('e5', 'clause-3', 'signature-payee'),
      createEdge('e6', 'signature-payer', 'payee-1'),
      createEdge('e7', 'signature-payee', 'payee-1'),
    ],
  },
  {
    id: 'master-service-agreement',
    name: 'Master Service Agreement',
    description: 'Umbrella terms that govern multiple SOWs with standard legal provisions.',
    icon: 'FileStack',
    category: 'legal',
    tags: ['legal'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 225 }, { label: 'Client', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 75 }, { label: 'Services', title: 'Services Overview', content: 'Provider will perform services as described in individual Statements of Work (SOWs) executed under this Agreement. Each SOW incorporates these terms.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 175 }, { label: 'Payment Terms', title: 'Payment', content: 'Payment terms per SOW. Net 30 invoicing. Late payments accrue 1.5% monthly interest.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 275 }, { label: 'IP Rights', title: 'Intellectual Property', content: 'Work product ownership transfers to Client upon full payment. Provider retains rights to pre-existing materials and general know-how.', aiGenerated: false }),
      createNode('clause-4', 'clause', { x: 350, y: 375 }, { label: 'Liability', title: 'Limitation of Liability', content: 'Neither party liable for indirect, consequential damages. Total liability capped at fees paid in prior 12 months.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 175 }, { label: 'Client Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Provider Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 225 }, { label: 'Service Provider', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'clause-4'),
      createEdge('e5', 'clause-4', 'signature-payer'),
      createEdge('e6', 'clause-4', 'signature-payee'),
      createEdge('e7', 'signature-payer', 'payee-1'),
      createEdge('e8', 'signature-payee', 'payee-1'),
    ],
  },
  {
    id: 'data-processing-agreement',
    name: 'Data Processing Agreement (DPA)',
    description: 'GDPR/CCPA compliant with data categories, breach notification, and sub-processor terms.',
    icon: 'Database',
    category: 'legal',
    tags: ['legal'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 225 }, { label: 'Data Controller', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 75 }, { label: 'Data Categories', title: 'Personal Data Processed', content: 'Categories: Contact info, usage data, payment info. Data subjects: End users, employees. Purpose: Service delivery per main agreement.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 175 }, { label: 'Security', title: 'Security Measures', content: 'Processor implements: encryption at rest/transit, access controls, regular audits, employee training. SOC 2 Type II certified.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 275 }, { label: 'Breach Notice', title: 'Breach Notification', content: 'Processor notifies Controller within 24 hours of discovering any personal data breach. Full incident report within 72 hours.', aiGenerated: false }),
      createNode('clause-4', 'clause', { x: 350, y: 375 }, { label: 'Sub-processors', title: 'Sub-processor Terms', content: 'Current sub-processors listed in Annex. 30 days notice before adding new sub-processors. Controller may object with reasonable grounds.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 175 }, { label: 'Controller Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Processor Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 225 }, { label: 'Data Processor', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'clause-4'),
      createEdge('e5', 'clause-4', 'signature-payer'),
      createEdge('e6', 'clause-4', 'signature-payee'),
      createEdge('e7', 'signature-payer', 'payee-1'),
      createEdge('e8', 'signature-payee', 'payee-1'),
    ],
  },

  // ============================================
  // FUNDRAISING TEMPLATES (2) - Investment instruments
  // ============================================

  {
    id: 'safe',
    name: 'SAFE (Post-Money)',
    description: 'YC-standard post-money SAFE with valuation cap, discount, and pro-rata rights.',
    icon: 'Rocket',
    category: 'fundraising',
    tags: ['legal'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Investor', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 100 }, { label: 'Investment Amount', title: 'Purchase Amount', content: 'Investor purchases the right to future equity for $[AMOUNT]. This is a post-money SAFE per Y Combinator standard.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 225 }, { label: 'Valuation Cap', title: 'Valuation Cap', content: 'Valuation Cap: $[CAP]. Discount Rate: 20%. If Equity Financing occurs, SAFE converts at the lower of (a) cap or (b) discount to price.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 350 }, { label: 'Pro-Rata', title: 'Pro-Rata Rights', content: 'Investor has pro-rata rights to participate in future financing rounds to maintain ownership percentage, subject to $[MIN] threshold.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 150 }, { label: 'Investor Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Company Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 225 }, { label: 'Company', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'signature-payer'),
      createEdge('e5', 'clause-3', 'signature-payee'),
      createEdge('e6', 'signature-payer', 'payee-1'),
      createEdge('e7', 'signature-payee', 'payee-1'),
    ],
  },
  {
    id: 'convertible-note',
    name: 'Convertible Note',
    description: 'Debt instrument with principal, interest rate, maturity date, and cap/discount conversion.',
    icon: 'Receipt',
    category: 'fundraising',
    tags: ['legal', 'payment', 'ai-escrow'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Investor', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 75 }, { label: 'Principal', title: 'Loan Terms', content: 'Principal Amount: $[AMOUNT]. Interest Rate: 5% per annum, simple interest. This note evidences a loan to Company.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 175 }, { label: 'Maturity', title: 'Maturity Date', content: 'Maturity Date: 24 months from issuance. At maturity, if not converted, Company repays principal plus accrued interest or converts at Holder option.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 275 }, { label: 'Conversion', title: 'Conversion Terms', content: 'Converts upon Qualified Financing ($1M+) at lesser of: (a) Valuation Cap: $[CAP] or (b) 20% discount to financing price.', aiGenerated: false }),
      createNode('milestone-1', 'milestone', { x: 600, y: 200 }, { label: 'Investment', title: 'Note Purchase', description: 'Wire transfer of principal amount', amount: 100000, currency: 'USDC', verificationCriteria: 'Funds received in company account' }),
      createNode('signature-payer', 'signature', { x: 850, y: 125 }, { label: 'Investor Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 850, y: 275 }, { label: 'Company Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 1100, y: 200 }, { label: 'Company', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'milestone-1'),
      createEdge('e5', 'milestone-1', 'signature-payer'),
      createEdge('e6', 'milestone-1', 'signature-payee'),
      createEdge('e7', 'signature-payer', 'payee-1'),
      createEdge('e8', 'signature-payee', 'payee-1'),
    ],
  },

  // ============================================
  // ONBOARDING TEMPLATES (3) - Creates CRM records
  // ============================================

  {
    id: 'contractor-agreement',
    name: 'Contractor Agreement',
    description: 'Full scope agreement with optional escrow, embedded IP assignment, and NDA. Creates a contractor record.',
    icon: 'UserCheck',
    category: 'onboarding',
    tags: ['legal', 'payment', 'ai-escrow', 'onboarding'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 225 }, { label: 'Company', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 75 }, { label: 'Services', title: 'Scope of Services', content: 'Contractor will provide services as described in attached Exhibit A. Contractor is an independent contractor, not an employee.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 175 }, { label: 'IP Assignment', title: 'Work Product', content: 'All work product created during engagement is work-for-hire and owned by Company. Contractor assigns all rights, title, and interest.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 275 }, { label: 'Confidentiality', title: 'NDA Terms', content: 'Contractor will maintain confidentiality of all Company information. Obligations survive termination for 3 years.', aiGenerated: false }),
      createNode('milestone-1', 'milestone', { x: 600, y: 175 }, { label: 'Monthly Payment', title: 'Monthly Contractor Fee', description: 'Monthly service fee for contracted work', amount: 10000, currency: 'USDC', verificationCriteria: 'Monthly deliverables completed' }),
      createNode('signature-payer', 'signature', { x: 850, y: 125 }, { label: 'Company Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 850, y: 275 }, { label: 'Contractor Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payment-1', 'payment', { x: 1100, y: 175 }, { label: 'Monthly Payment', amount: 10000, currency: 'USDC', triggerType: 'time-based' }),
      createNode('payee-1', 'party-payee', { x: 1350, y: 175 }, { label: 'Contractor', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'milestone-1'),
      createEdge('e5', 'milestone-1', 'signature-payer'),
      createEdge('e6', 'milestone-1', 'signature-payee'),
      createEdge('e7', 'signature-payer', 'payment-1'),
      createEdge('e8', 'signature-payee', 'payment-1'),
      createEdge('e9', 'payment-1', 'payee-1'),
    ],
  },
  {
    id: 'advisor-agreement',
    name: 'Advisor Agreement',
    description: 'Equity grant with vesting schedule, commitment hours, and standard advisor terms. Creates an advisor record.',
    icon: 'GraduationCap',
    category: 'onboarding',
    tags: ['legal', 'onboarding'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 200 }, { label: 'Company', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 100 }, { label: 'Advisory Role', title: 'Advisory Services', content: 'Advisor will provide strategic guidance, introductions, and expertise in [AREA]. Expected commitment: 2-4 hours per month.', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 225 }, { label: 'Equity Grant', title: 'Stock Option Grant', content: 'Advisor receives option to purchase [X]% of common stock. Vesting: 24 months, monthly, with 3-month cliff. Exercise price: FMV at grant.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 350 }, { label: 'Confidentiality', title: 'Confidentiality & Non-Compete', content: 'Advisor maintains confidentiality and will not advise direct competitors during engagement and for 12 months after.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 150 }, { label: 'Company Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Advisor Signature', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 225 }, { label: 'Advisor', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'signature-payer'),
      createEdge('e5', 'clause-3', 'signature-payee'),
      createEdge('e6', 'signature-payer', 'payee-1'),
      createEdge('e7', 'signature-payee', 'payee-1'),
    ],
  },
  {
    id: 'offer-letter',
    name: 'Offer Letter',
    description: 'Employment offer with salary, equity package, crypto payment option, and at-will terms. Creates an employee record.',
    icon: 'Mail',
    category: 'onboarding',
    tags: ['legal', 'onboarding'],
    nodes: [
      createNode('payer-1', 'party-payer', { x: 100, y: 225 }, { label: 'Company', name: '', email: '', role: 'payer' }),
      createNode('clause-1', 'clause', { x: 350, y: 75 }, { label: 'Position', title: 'Position & Start Date', content: 'Position: [TITLE]. Department: [DEPT]. Reports to: [MANAGER]. Start Date: [DATE]. Location: [LOCATION/Remote].', aiGenerated: false }),
      createNode('clause-2', 'clause', { x: 350, y: 175 }, { label: 'Compensation', title: 'Salary & Benefits', content: 'Base Salary: $[AMOUNT]/year, paid bi-weekly. Crypto payment option: Up to 50% in USDC. Benefits: Health, dental, vision, 401k match.', aiGenerated: false }),
      createNode('clause-3', 'clause', { x: 350, y: 275 }, { label: 'Equity', title: 'Equity Package', content: 'Stock Options: [X] shares, 4-year vesting with 1-year cliff. Strike price determined at board approval.', aiGenerated: false }),
      createNode('clause-4', 'clause', { x: 350, y: 375 }, { label: 'At-Will', title: 'Employment Terms', content: 'Employment is at-will. Either party may terminate with 2 weeks notice. Subject to PIIA execution on start date.', aiGenerated: false }),
      createNode('signature-payer', 'signature', { x: 600, y: 175 }, { label: 'Company Signature', required: true, signerId: '', signerRole: 'payer', signerEmail: '' }),
      createNode('signature-payee', 'signature', { x: 600, y: 300 }, { label: 'Employee Acceptance', required: true, signerId: '', signerRole: 'payee', signerEmail: '' }),
      createNode('payee-1', 'party-payee', { x: 850, y: 225 }, { label: 'Employee', name: '', email: '', role: 'payee' }),
    ],
    edges: [
      createEdge('e1', 'payer-1', 'clause-1'),
      createEdge('e2', 'clause-1', 'clause-2'),
      createEdge('e3', 'clause-2', 'clause-3'),
      createEdge('e4', 'clause-3', 'clause-4'),
      createEdge('e5', 'clause-4', 'signature-payer'),
      createEdge('e6', 'clause-4', 'signature-payee'),
      createEdge('e7', 'signature-payer', 'payee-1'),
      createEdge('e8', 'signature-payee', 'payee-1'),
    ],
  },
]

// ── Category & Tag metadata ──────────────
import type { ContractCategory, ContractTag } from '@/packages/flow'

export const categoryLabels: Record<ContractCategory, string> = {
  payment: 'Payment',
  onboarding: 'Onboarding',
  fundraising: 'Fundraising',
  legal: 'Legal',
}

export const categoryColors: Record<ContractCategory, string> = {
  payment: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20',
  onboarding: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/20',
  fundraising: 'bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20',
  legal: 'bg-zinc-500/10 text-zinc-600 dark:text-zinc-400 border-zinc-500/20',
}

export const tagLabels: Record<ContractTag, string> = {
  legal: 'Legal',
  payment: 'Payment',
  'ai-escrow': 'AI Escrow',
  onboarding: 'Onboarding',
}

export const tagColors: Record<ContractTag, string> = {
  legal: 'bg-zinc-500/10 text-zinc-600 dark:text-zinc-400 border-zinc-500/20',
  payment: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20',
  'ai-escrow': 'bg-violet-500/10 text-violet-600 dark:text-violet-400 border-violet-500/20',
  onboarding: 'bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/20',
}

export function getTemplateById(id: string): ContractTemplate | undefined {
  return contractTemplates.find((t) => t.id === id)
}

export function getTemplatesByCategory(category: ContractCategory | 'all'): ContractTemplate[] {
  if (category === 'all') return contractTemplates
  return contractTemplates.filter((t) => t.category === category)
}

export function getTemplatesByTag(tag: ContractTag): ContractTemplate[] {
  return contractTemplates.filter((t) => t.tags.includes(tag))
}
