/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEscrowWithAgentV3 {
  export type MilestoneStruct = {
    amount: BigNumberish;
    released: BigNumberish;
    funded: boolean;
    locked: boolean;
    status: BigNumberish;
    disputeWindowEnd: BigNumberish;
    finalReceiptHash: BytesLike;
  };

  export type MilestoneStructOutput = [
    amount: bigint,
    released: bigint,
    funded: boolean,
    locked: boolean,
    status: bigint,
    disputeWindowEnd: bigint,
    finalReceiptHash: string
  ] & {
    amount: bigint;
    released: bigint;
    funded: boolean;
    locked: boolean;
    status: bigint;
    disputeWindowEnd: bigint;
    finalReceiptHash: string;
  };

  export type FeeConfigStruct = {
    protocolFeeBps: BigNumberish;
    protocolFeeRecipient: AddressLike;
  };

  export type FeeConfigStructOutput = [
    protocolFeeBps: bigint,
    protocolFeeRecipient: string
  ] & { protocolFeeBps: bigint; protocolFeeRecipient: string };

  export type AgentConfigStruct = {
    identityRegistry: AddressLike;
    executorAgentId: BigNumberish;
  };

  export type AgentConfigStructOutput = [
    identityRegistry: string,
    executorAgentId: bigint
  ] & { identityRegistry: string; executorAgentId: bigint };

  export type WindowConfigStruct = {
    disputeWindowSeconds: BigNumberish;
    appealWindowSeconds: BigNumberish;
  };

  export type WindowConfigStructOutput = [
    disputeWindowSeconds: bigint,
    appealWindowSeconds: bigint
  ] & { disputeWindowSeconds: bigint; appealWindowSeconds: bigint };

  export type PayoutStruct = { to: AddressLike; amount: BigNumberish };

  export type PayoutStructOutput = [to: string, amount: bigint] & {
    to: string;
    amount: bigint;
  };
}

export interface EscrowWithAgentV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "executeDecision"
      | "fees"
      | "fundMilestone"
      | "getDecision"
      | "getMilestone"
      | "getMilestoneCount"
      | "getPayee"
      | "getPayer"
      | "getToken"
      | "initialize"
      | "lockMilestone"
      | "milestones"
      | "payee"
      | "payer"
      | "setDecision"
      | "setMilestoneStatus"
      | "token"
      | "windows"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecisionExecuted"
      | "DecisionSet"
      | "DisputeWindowStarted"
      | "MilestoneFunded"
      | "MilestoneLocked"
      | "MilestoneStatusChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeDecision",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecision",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestoneCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPayee", values?: undefined): string;
  encodeFunctionData(functionFragment: "getPayer", values?: undefined): string;
  encodeFunctionData(functionFragment: "getToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      IEscrowWithAgentV3.FeeConfigStruct,
      IEscrowWithAgentV3.AgentConfigStruct,
      IEscrowWithAgentV3.WindowConfigStruct,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lockMilestone",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "payee", values?: undefined): string;
  encodeFunctionData(functionFragment: "payer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDecision",
    values: [
      BigNumberish,
      BigNumberish,
      IEscrowWithAgentV3.PayoutStruct[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMilestoneStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "windows", values?: undefined): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestoneCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMilestoneStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "windows", data: BytesLike): Result;
}

export namespace DecisionExecutedEvent {
  export type InputTuple = [
    milestoneIndex: BigNumberish,
    payeeAmount: BigNumberish,
    payerAmount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneIndex: bigint,
    payeeAmount: bigint,
    payerAmount: bigint
  ];
  export interface OutputObject {
    milestoneIndex: bigint;
    payeeAmount: bigint;
    payerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecisionSetEvent {
  export type InputTuple = [
    milestoneIndex: BigNumberish,
    payeeBps: BigNumberish,
    finalReceiptHash: BytesLike
  ];
  export type OutputTuple = [
    milestoneIndex: bigint,
    payeeBps: bigint,
    finalReceiptHash: string
  ];
  export interface OutputObject {
    milestoneIndex: bigint;
    payeeBps: bigint;
    finalReceiptHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeWindowStartedEvent {
  export type InputTuple = [
    milestoneIndex: BigNumberish,
    windowEnd: BigNumberish
  ];
  export type OutputTuple = [milestoneIndex: bigint, windowEnd: bigint];
  export interface OutputObject {
    milestoneIndex: bigint;
    windowEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneFundedEvent {
  export type InputTuple = [milestoneIndex: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [milestoneIndex: bigint, amount: bigint];
  export interface OutputObject {
    milestoneIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneLockedEvent {
  export type InputTuple = [
    milestoneIndex: BigNumberish,
    disputeHash: BytesLike
  ];
  export type OutputTuple = [milestoneIndex: bigint, disputeHash: string];
  export interface OutputObject {
    milestoneIndex: bigint;
    disputeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneStatusChangedEvent {
  export type InputTuple = [
    milestoneIndex: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [milestoneIndex: bigint, newStatus: bigint];
  export interface OutputObject {
    milestoneIndex: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowWithAgentV3 extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowWithAgentV3;
  waitForDeployment(): Promise<this>;

  interface: EscrowWithAgentV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [],
    [[string, bigint] & { identityRegistry: string; executorAgentId: bigint }],
    "view"
  >;

  executeDecision: TypedContractMethod<
    [milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  fees: TypedContractMethod<
    [],
    [
      [bigint, string] & {
        protocolFeeBps: bigint;
        protocolFeeRecipient: string;
      }
    ],
    "view"
  >;

  fundMilestone: TypedContractMethod<
    [milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDecision: TypedContractMethod<
    [milestoneIndex: BigNumberish],
    [
      [bigint, string, boolean, bigint] & {
        payeeBps: bigint;
        receiptHash: string;
        isSet: boolean;
        extraPayoutsCount: bigint;
      }
    ],
    "view"
  >;

  getMilestone: TypedContractMethod<
    [milestoneIndex: BigNumberish],
    [IEscrowWithAgentV3.MilestoneStructOutput],
    "view"
  >;

  getMilestoneCount: TypedContractMethod<[], [bigint], "view">;

  getPayee: TypedContractMethod<[], [string], "view">;

  getPayer: TypedContractMethod<[], [string], "view">;

  getToken: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      _payer: AddressLike,
      _payee: AddressLike,
      _token: AddressLike,
      _fees: IEscrowWithAgentV3.FeeConfigStruct,
      _agents: IEscrowWithAgentV3.AgentConfigStruct,
      _windows: IEscrowWithAgentV3.WindowConfigStruct,
      milestoneAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  lockMilestone: TypedContractMethod<
    [milestoneIndex: BigNumberish, disputeHash: BytesLike],
    [void],
    "nonpayable"
  >;

  milestones: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, boolean, bigint, bigint, string] & {
        amount: bigint;
        released: bigint;
        funded: boolean;
        locked: boolean;
        status: bigint;
        disputeWindowEnd: bigint;
        finalReceiptHash: string;
      }
    ],
    "view"
  >;

  payee: TypedContractMethod<[], [string], "view">;

  payer: TypedContractMethod<[], [string], "view">;

  setDecision: TypedContractMethod<
    [
      milestoneIndex: BigNumberish,
      payeeBps: BigNumberish,
      extraPayouts: IEscrowWithAgentV3.PayoutStruct[],
      finalReceiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setMilestoneStatus: TypedContractMethod<
    [milestoneIndex: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  windows: TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        disputeWindowSeconds: bigint;
        appealWindowSeconds: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { identityRegistry: string; executorAgentId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeDecision"
  ): TypedContractMethod<[milestoneIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fees"
  ): TypedContractMethod<
    [],
    [
      [bigint, string] & {
        protocolFeeBps: bigint;
        protocolFeeRecipient: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundMilestone"
  ): TypedContractMethod<[milestoneIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDecision"
  ): TypedContractMethod<
    [milestoneIndex: BigNumberish],
    [
      [bigint, string, boolean, bigint] & {
        payeeBps: bigint;
        receiptHash: string;
        isSet: boolean;
        extraPayoutsCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [milestoneIndex: BigNumberish],
    [IEscrowWithAgentV3.MilestoneStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestoneCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _payer: AddressLike,
      _payee: AddressLike,
      _token: AddressLike,
      _fees: IEscrowWithAgentV3.FeeConfigStruct,
      _agents: IEscrowWithAgentV3.AgentConfigStruct,
      _windows: IEscrowWithAgentV3.WindowConfigStruct,
      milestoneAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockMilestone"
  ): TypedContractMethod<
    [milestoneIndex: BigNumberish, disputeHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, boolean, bigint, bigint, string] & {
        amount: bigint;
        released: bigint;
        funded: boolean;
        locked: boolean;
        status: bigint;
        disputeWindowEnd: bigint;
        finalReceiptHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "payee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDecision"
  ): TypedContractMethod<
    [
      milestoneIndex: BigNumberish,
      payeeBps: BigNumberish,
      extraPayouts: IEscrowWithAgentV3.PayoutStruct[],
      finalReceiptHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMilestoneStatus"
  ): TypedContractMethod<
    [milestoneIndex: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "windows"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        disputeWindowSeconds: bigint;
        appealWindowSeconds: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DecisionExecuted"
  ): TypedContractEvent<
    DecisionExecutedEvent.InputTuple,
    DecisionExecutedEvent.OutputTuple,
    DecisionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DecisionSet"
  ): TypedContractEvent<
    DecisionSetEvent.InputTuple,
    DecisionSetEvent.OutputTuple,
    DecisionSetEvent.OutputObject
  >;
  getEvent(
    key: "DisputeWindowStarted"
  ): TypedContractEvent<
    DisputeWindowStartedEvent.InputTuple,
    DisputeWindowStartedEvent.OutputTuple,
    DisputeWindowStartedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneFunded"
  ): TypedContractEvent<
    MilestoneFundedEvent.InputTuple,
    MilestoneFundedEvent.OutputTuple,
    MilestoneFundedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneLocked"
  ): TypedContractEvent<
    MilestoneLockedEvent.InputTuple,
    MilestoneLockedEvent.OutputTuple,
    MilestoneLockedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneStatusChanged"
  ): TypedContractEvent<
    MilestoneStatusChangedEvent.InputTuple,
    MilestoneStatusChangedEvent.OutputTuple,
    MilestoneStatusChangedEvent.OutputObject
  >;

  filters: {
    "DecisionExecuted(uint256,uint256,uint256)": TypedContractEvent<
      DecisionExecutedEvent.InputTuple,
      DecisionExecutedEvent.OutputTuple,
      DecisionExecutedEvent.OutputObject
    >;
    DecisionExecuted: TypedContractEvent<
      DecisionExecutedEvent.InputTuple,
      DecisionExecutedEvent.OutputTuple,
      DecisionExecutedEvent.OutputObject
    >;

    "DecisionSet(uint256,uint16,bytes32)": TypedContractEvent<
      DecisionSetEvent.InputTuple,
      DecisionSetEvent.OutputTuple,
      DecisionSetEvent.OutputObject
    >;
    DecisionSet: TypedContractEvent<
      DecisionSetEvent.InputTuple,
      DecisionSetEvent.OutputTuple,
      DecisionSetEvent.OutputObject
    >;

    "DisputeWindowStarted(uint256,uint256)": TypedContractEvent<
      DisputeWindowStartedEvent.InputTuple,
      DisputeWindowStartedEvent.OutputTuple,
      DisputeWindowStartedEvent.OutputObject
    >;
    DisputeWindowStarted: TypedContractEvent<
      DisputeWindowStartedEvent.InputTuple,
      DisputeWindowStartedEvent.OutputTuple,
      DisputeWindowStartedEvent.OutputObject
    >;

    "MilestoneFunded(uint256,uint256)": TypedContractEvent<
      MilestoneFundedEvent.InputTuple,
      MilestoneFundedEvent.OutputTuple,
      MilestoneFundedEvent.OutputObject
    >;
    MilestoneFunded: TypedContractEvent<
      MilestoneFundedEvent.InputTuple,
      MilestoneFundedEvent.OutputTuple,
      MilestoneFundedEvent.OutputObject
    >;

    "MilestoneLocked(uint256,bytes32)": TypedContractEvent<
      MilestoneLockedEvent.InputTuple,
      MilestoneLockedEvent.OutputTuple,
      MilestoneLockedEvent.OutputObject
    >;
    MilestoneLocked: TypedContractEvent<
      MilestoneLockedEvent.InputTuple,
      MilestoneLockedEvent.OutputTuple,
      MilestoneLockedEvent.OutputObject
    >;

    "MilestoneStatusChanged(uint256,uint8)": TypedContractEvent<
      MilestoneStatusChangedEvent.InputTuple,
      MilestoneStatusChangedEvent.OutputTuple,
      MilestoneStatusChangedEvent.OutputObject
    >;
    MilestoneStatusChanged: TypedContractEvent<
      MilestoneStatusChangedEvent.InputTuple,
      MilestoneStatusChangedEvent.OutputTuple,
      MilestoneStatusChangedEvent.OutputObject
    >;
  };
}
