/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEscrowWithAgentV3 {
  export type FeeConfigStruct = {
    protocolFeeBps: BigNumberish;
    protocolFeeRecipient: AddressLike;
  };

  export type FeeConfigStructOutput = [
    protocolFeeBps: bigint,
    protocolFeeRecipient: string
  ] & { protocolFeeBps: bigint; protocolFeeRecipient: string };

  export type AgentConfigStruct = {
    identityRegistry: AddressLike;
    executorAgentId: BigNumberish;
  };

  export type AgentConfigStructOutput = [
    identityRegistry: string,
    executorAgentId: bigint
  ] & { identityRegistry: string; executorAgentId: bigint };

  export type WindowConfigStruct = {
    disputeWindowSeconds: BigNumberish;
    appealWindowSeconds: BigNumberish;
  };

  export type WindowConfigStructOutput = [
    disputeWindowSeconds: bigint,
    appealWindowSeconds: bigint
  ] & { disputeWindowSeconds: bigint; appealWindowSeconds: bigint };
}

export interface EscrowFactoryV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptedTokens"
      | "allEscrows"
      | "createAgreement"
      | "escrows"
      | "getEscrow"
      | "getEscrowCount"
      | "implementation"
      | "owner"
      | "setTokenAccepted"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgreementCreated" | "TokenWhitelisted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allEscrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      IEscrowWithAgentV3.FeeConfigStruct,
      IEscrowWithAgentV3.AgentConfigStruct,
      IEscrowWithAgentV3.WindowConfigStruct,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setTokenAccepted",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allEscrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAccepted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    escrowAddress: AddressLike,
    token: AddressLike,
    payer: AddressLike,
    payee: AddressLike,
    milestoneCount: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    escrowAddress: string,
    token: string,
    payer: string,
    payee: string,
    milestoneCount: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    escrowAddress: string;
    token: string;
    payer: string;
    payee: string;
    milestoneCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWhitelistedEvent {
  export type InputTuple = [token: AddressLike, accepted: boolean];
  export type OutputTuple = [token: string, accepted: boolean];
  export interface OutputObject {
    token: string;
    accepted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowFactoryV3 extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowFactoryV3;
  waitForDeployment(): Promise<this>;

  interface: EscrowFactoryV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  allEscrows: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createAgreement: TypedContractMethod<
    [
      agreementId: BytesLike,
      _payer: AddressLike,
      _payee: AddressLike,
      _token: AddressLike,
      _fees: IEscrowWithAgentV3.FeeConfigStruct,
      _agents: IEscrowWithAgentV3.AgentConfigStruct,
      _windows: IEscrowWithAgentV3.WindowConfigStruct,
      milestoneAmounts: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;

  escrows: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEscrow: TypedContractMethod<[agreementId: BytesLike], [string], "view">;

  getEscrowCount: TypedContractMethod<[], [bigint], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setTokenAccepted: TypedContractMethod<
    [_token: AddressLike, _accepted: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "allEscrows"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      _payer: AddressLike,
      _payee: AddressLike,
      _token: AddressLike,
      _fees: IEscrowWithAgentV3.FeeConfigStruct,
      _agents: IEscrowWithAgentV3.AgentConfigStruct,
      _windows: IEscrowWithAgentV3.WindowConfigStruct,
      milestoneAmounts: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<[agreementId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEscrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setTokenAccepted"
  ): TypedContractMethod<
    [_token: AddressLike, _accepted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWhitelisted"
  ): TypedContractEvent<
    TokenWhitelistedEvent.InputTuple,
    TokenWhitelistedEvent.OutputTuple,
    TokenWhitelistedEvent.OutputObject
  >;

  filters: {
    "AgreementCreated(bytes32,address,address,address,address,uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "TokenWhitelisted(address,bool)": TypedContractEvent<
      TokenWhitelistedEvent.InputTuple,
      TokenWhitelistedEvent.OutputTuple,
      TokenWhitelistedEvent.OutputObject
    >;
    TokenWhitelisted: TypedContractEvent<
      TokenWhitelistedEvent.InputTuple,
      TokenWhitelistedEvent.OutputTuple,
      TokenWhitelistedEvent.OutputObject
    >;
  };
}
