/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExtractor,
  IExtractorInterface,
} from "../../../../../contracts/bufi/extractors/EscrowExtractor.sol/IExtractor";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "bytes4",
            name: "selector",
            type: "bytes4",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct IPolicyEngine.Payload",
        name: "payload",
        type: "tuple",
      },
    ],
    name: "extract",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "name",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "value",
            type: "bytes",
          },
        ],
        internalType: "struct IPolicyEngine.Parameter[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IExtractor__factory {
  static readonly abi = _abi;
  static createInterface(): IExtractorInterface {
    return new Interface(_abi) as IExtractorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IExtractor {
    return new Contract(address, _abi, runner) as unknown as IExtractor;
  }
}
