/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace IPolicyEngine {
  export type PayloadStruct = {
    target: AddressLike;
    selector: BytesLike;
    data: BytesLike;
  };

  export type PayloadStructOutput = [
    target: string,
    selector: string,
    data: string
  ] & { target: string; selector: string; data: string };

  export type ParameterStruct = { name: BytesLike; value: BytesLike };

  export type ParameterStructOutput = [name: string, value: string] & {
    name: string;
    value: string;
  };
}

export interface EscrowExtractorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACTION_EXECUTE"
      | "ACTION_FUND"
      | "ACTION_LOCK"
      | "ACTION_SET_DECISION"
      | "ACTION_STATUS"
      | "PARAM_ACTION_TYPE"
      | "PARAM_EXECUTOR_AGENT"
      | "PARAM_MILESTONE_INDEX"
      | "PARAM_PAYEE_BPS"
      | "PARAM_RECEIPT_HASH"
      | "extract"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ACTION_EXECUTE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_FUND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_LOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_SET_DECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ACTION_STATUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_ACTION_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_EXECUTOR_AGENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_MILESTONE_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_PAYEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARAM_RECEIPT_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extract",
    values: [IPolicyEngine.PayloadStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACTION_EXECUTE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_FUND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_LOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_SET_DECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ACTION_STATUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_ACTION_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_EXECUTOR_AGENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_MILESTONE_INDEX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_PAYEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARAM_RECEIPT_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "extract", data: BytesLike): Result;
}

export interface EscrowExtractor extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowExtractor;
  waitForDeployment(): Promise<this>;

  interface: EscrowExtractorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACTION_EXECUTE: TypedContractMethod<[], [bigint], "view">;

  ACTION_FUND: TypedContractMethod<[], [bigint], "view">;

  ACTION_LOCK: TypedContractMethod<[], [bigint], "view">;

  ACTION_SET_DECISION: TypedContractMethod<[], [bigint], "view">;

  ACTION_STATUS: TypedContractMethod<[], [bigint], "view">;

  PARAM_ACTION_TYPE: TypedContractMethod<[], [string], "view">;

  PARAM_EXECUTOR_AGENT: TypedContractMethod<[], [string], "view">;

  PARAM_MILESTONE_INDEX: TypedContractMethod<[], [string], "view">;

  PARAM_PAYEE_BPS: TypedContractMethod<[], [string], "view">;

  PARAM_RECEIPT_HASH: TypedContractMethod<[], [string], "view">;

  extract: TypedContractMethod<
    [payload: IPolicyEngine.PayloadStruct],
    [IPolicyEngine.ParameterStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACTION_EXECUTE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACTION_FUND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACTION_LOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACTION_SET_DECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ACTION_STATUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARAM_ACTION_TYPE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PARAM_EXECUTOR_AGENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PARAM_MILESTONE_INDEX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PARAM_PAYEE_BPS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PARAM_RECEIPT_HASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "extract"
  ): TypedContractMethod<
    [payload: IPolicyEngine.PayloadStruct],
    [IPolicyEngine.ParameterStructOutput[]],
    "view"
  >;

  filters: {};
}
