/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace IPolicyEngine {
  export type PayloadStruct = {
    target: AddressLike;
    selector: BytesLike;
    data: BytesLike;
  };

  export type PayloadStructOutput = [
    target: string,
    selector: string,
    data: string
  ] & { target: string; selector: string; data: string };

  export type ParameterStruct = { name: BytesLike; value: BytesLike };

  export type ParameterStructOutput = [name: string, value: string] & {
    name: string;
    value: string;
  };
}

export interface IExtractorInterface extends Interface {
  getFunction(nameOrSignature: "extract"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "extract",
    values: [IPolicyEngine.PayloadStruct]
  ): string;

  decodeFunctionResult(functionFragment: "extract", data: BytesLike): Result;
}

export interface IExtractor extends BaseContract {
  connect(runner?: ContractRunner | null): IExtractor;
  waitForDeployment(): Promise<this>;

  interface: IExtractorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  extract: TypedContractMethod<
    [payload: IPolicyEngine.PayloadStruct],
    [IPolicyEngine.ParameterStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "extract"
  ): TypedContractMethod<
    [payload: IPolicyEngine.PayloadStruct],
    [IPolicyEngine.ParameterStructOutput[]],
    "view"
  >;

  filters: {};
}
