/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEscrowWithAgentV3,
  IEscrowWithAgentV3Interface,
} from "../../../contracts/bufi/IEscrowWithAgentV3";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payeeAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payerAmount",
        type: "uint256",
      },
    ],
    name: "DecisionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "payeeBps",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "finalReceiptHash",
        type: "bytes32",
      },
    ],
    name: "DecisionSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "windowEnd",
        type: "uint256",
      },
    ],
    name: "DisputeWindowStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "MilestoneFunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "disputeHash",
        type: "bytes32",
      },
    ],
    name: "MilestoneLocked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum IEscrowWithAgentV3.MilestoneStatus",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "MilestoneStatusChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
    ],
    name: "executeDecision",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
    ],
    name: "fundMilestone",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
    ],
    name: "getMilestone",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "released",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "funded",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "locked",
            type: "bool",
          },
          {
            internalType: "enum IEscrowWithAgentV3.MilestoneStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "disputeWindowEnd",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "finalReceiptHash",
            type: "bytes32",
          },
        ],
        internalType: "struct IEscrowWithAgentV3.Milestone",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMilestoneCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPayee",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPayer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "payee",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "protocolFeeBps",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "protocolFeeRecipient",
            type: "address",
          },
        ],
        internalType: "struct IEscrowWithAgentV3.FeeConfig",
        name: "fees",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "identityRegistry",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "executorAgentId",
            type: "uint256",
          },
        ],
        internalType: "struct IEscrowWithAgentV3.AgentConfig",
        name: "agents",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint32",
            name: "disputeWindowSeconds",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "appealWindowSeconds",
            type: "uint32",
          },
        ],
        internalType: "struct IEscrowWithAgentV3.WindowConfig",
        name: "windows",
        type: "tuple",
      },
      {
        internalType: "uint256[]",
        name: "milestoneAmounts",
        type: "uint256[]",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "disputeHash",
        type: "bytes32",
      },
    ],
    name: "lockMilestone",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "payeeBps",
        type: "uint16",
      },
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct IEscrowWithAgentV3.Payout[]",
        name: "extraPayouts",
        type: "tuple[]",
      },
      {
        internalType: "bytes32",
        name: "finalReceiptHash",
        type: "bytes32",
      },
    ],
    name: "setDecision",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "milestoneIndex",
        type: "uint256",
      },
      {
        internalType: "enum IEscrowWithAgentV3.MilestoneStatus",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "setMilestoneStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEscrowWithAgentV3__factory {
  static readonly abi = _abi;
  static createInterface(): IEscrowWithAgentV3Interface {
    return new Interface(_abi) as IEscrowWithAgentV3Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEscrowWithAgentV3 {
    return new Contract(address, _abi, runner) as unknown as IEscrowWithAgentV3;
  }
}
