/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC8004IdentityMinimal,
  IERC8004IdentityMinimalInterface,
} from "../../../../../contracts/bufi/policies/AgentIdentityPolicy.sol/IERC8004IdentityMinimal";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC8004IdentityMinimal__factory {
  static readonly abi = _abi;
  static createInterface(): IERC8004IdentityMinimalInterface {
    return new Interface(_abi) as IERC8004IdentityMinimalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC8004IdentityMinimal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC8004IdentityMinimal;
  }
}
